// Curriculum loader. Source of truth: the Airtable Lessons table (view "2026 | Lessons").
// With AIRTABLE_TOKEN set, the server reads Airtable at launch and re-reads it when the
// cache is older than TTL_MS. Without a token, or if Airtable is unreachable, it serves
// the committed snapshot in data/curriculum.json (generated by scripts/sync-curriculum.js).
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SNAPSHOT = path.resolve(ROOT, 'data', 'curriculum.json');
const BASE = 'appnHZYcirCg1VqUP';
const TABLES = { lessons: 'tblxZy7RMJ2naoHhS', speakers: 'tblp41QdehEIDh5KF', modules: 'tbl3kewb2Z7fEIkFl' };
const VIEW = 'viwzNbQ73gtCPFIl0';
const TTL_MS = Number(process.env.CURRICULUM_TTL_MS || 10 * 60 * 1000);

const MODULES = [
  'Pillar 1: Message & Positioning', 'Pillar 2: Platform & Content', 'Pillar 3: Funnel & Conversion',
  'Pillar 4: Scale & Products', 'Pillar 5: Legacy & Systems',
];
const IMAGE_ALIAS = { Vishen: 'vishen-lakhiani.jpg' };
const slug = (t) => String(t).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

function speaker(name) {
  const file = IMAGE_ALIAS[name] || slug(name) + '.jpg';
  const has = fs.existsSync(path.resolve(ROOT, 'authors', file));
  return { name: name === 'Vishen' ? 'Vishen Lakhiani' : name, image: has ? 'authors/' + file : null };
}

async function airtable(table, params) {
  const token = process.env.AIRTABLE_TOKEN;
  const out = [];
  let offset;
  do {
    const url = new URL(`https://api.airtable.com/v0/${BASE}/${table}`);
    Object.entries(params || {}).forEach(([k, v]) => url.searchParams.set(k, v));
    url.searchParams.set('pageSize', '100');
    if (offset) url.searchParams.set('offset', offset);
    const res = await fetch(url, { headers: { Authorization: 'Bearer ' + token } });
    if (!res.ok) throw new Error(`Airtable ${table} ${res.status}`);
    const json = await res.json();
    out.push(...json.records);
    offset = json.offset;
  } while (offset);
  return out;
}

function normalize(lessons, speakers, modules) {
  const spk = Object.fromEntries(speakers.map((r) => [r.id, r.fields.Name]));
  const mod = Object.fromEntries(modules.map((r) => [r.id, r.fields.Module]));
  const sessions = lessons
    .filter((r) => r.fields['Lesson Title'])
    .map((r) => {
      const f = r.fields;
      const cover = (f.Covers || [])[0];
      const start = (f['Date & Time [Pacific Time]'] || [])[0] || null;
      return {
        id: r.id,
        slot: (f.Slot || []).length ? null : null, // slot names need another lookup; not shown on the page
        title: String(f['Lesson Title']).trim(),
        type: f.Type || null,
        status: f.Status || null,
        start,
        duration_min: f.Duration ? Math.round(f.Duration / 60) : null,
        speakers: (f.Speaker || []).map((id) => speaker(spk[id] || 'Speaker')),
        module: (f.Module || []).map((id) => mod[id])[0] || null,
        description: (f.Description || '').trim(),
        cover: cover ? ((cover.thumbnails && cover.thumbnails.large && cover.thumbnails.large.url) || cover.url) : null,
        feedback_url: (f['Feedback Form URL'] || [])[0] || null,
      };
    })
    .sort((a, b) => (a.start || '9999').localeCompare(b.start || '9999') || (a.type === 'Workshop') - (b.type === 'Workshop'));
  return {
    source: { base: BASE, table: TABLES.lessons, view: VIEW, url: `https://airtable.com/${BASE}/${TABLES.lessons}/${VIEW}`, label: 'Expert to Authority · Lessons · 2026 | Lessons' },
    mode: 'live',
    synced_at: new Date().toISOString().replace(/\.\d+Z$/, 'Z'),
    modules: MODULES.map((name, i) => ({ name, short: name.split(': ')[1], order: i + 1 })),
    sessions,
  };
}

async function fetchLive() {
  const [lessons, speakers, modules] = await Promise.all([
    airtable(TABLES.lessons, { view: VIEW }),
    airtable(TABLES.speakers, {}),
    airtable(TABLES.modules, {}),
  ]);
  return normalize(lessons, speakers, modules);
}

function snapshot() {
  const data = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
  data.mode = 'snapshot';
  return data;
}

let cache = null; // { data, at }
let inflight = null;

async function load() {
  if (!process.env.AIRTABLE_TOKEN) return snapshot();
  const fresh = cache && Date.now() - cache.at < TTL_MS;
  if (fresh) return cache.data;
  if (!inflight) {
    inflight = fetchLive()
      .then((data) => { cache = { data, at: Date.now() }; return data; })
      .catch((err) => {
        console.error('curriculum: Airtable read failed, serving ' + (cache ? 'last good copy' : 'snapshot') + ':', err.message);
        return cache ? cache.data : snapshot();
      })
      .finally(() => { inflight = null; });
  }
  return inflight;
}

module.exports = { load, fetchLive, snapshot, normalize };
